apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: "{{ $.Values.name }}-secrets"
  namespace: flux-system
  annotations:
    "helm.sh/hook-weight": "0"
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./secrets_terraform
  sourceRef:
    kind: GitRepository
    name: terraform-gitops
    namespace: flux-system
  vars:
  - name: name
    value: {{ $.Values.name }}
  - name: registry_username
    value: "a54c0f1b-ab10-498c-9465-654a7cdbb3bc"
  - name: registry_password
    value: "c7W8Q~NpIO4whSj_XRe9~ah7uA_m10BL98lhmak5"
  - name: registry_server
    value: "{{ $.Values.name }}.azurecr.io"
  - name: cluster_name
    value: "celz-aks"
  - name: cluster_resource_group
    value: "celz"
  dependsOn:
  - name: "{{ $.Values.name }}-acrrepository"
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-service-principal
