{{- range $user := .Values.users }}
{{- if $user.externalSecretName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $user.externalSecretName }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: {{ $user.externalSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ $user.externalSecretName }}
    remoteRef:
      key: secret/{{ $user.externalSecretName }}
{{- end -}}
{{- end -}}
