# {{- if eq .Values.repoType "springboot-restservice" }}
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: "{{ .Values.name }}-openapichanger"
#   namespace: "{{ .Release.Namespace }}"
#   labels:
#   annotations:
#     "helm.sh/hook-weight": "0"
# spec:
#   template:
#     metadata:
#       name: "{{ .Values.name }}"
#     spec:
#       restartPolicy: Never
#       containers:
#       - name: "{{ .Values.name }}"
#         image: alpine
#         env:
#         - name: APPLICATION_NAME
#           value: "{{ .Values.repoName }}"
#         - name: ORGANIZATION_NAME
#           value: "{{ .Values.organizationName }}"
#         command:
#         - /bin/sh
#         - -c
#         - |
#           # Install git
#           apk add git

#           # Set variables
#           git_username="github-actions[bot]"
#           git_token="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"

#           # Clone the repos
#           git clone https://$git_username:$git_token@github.com/$ORGANIZATION_NAME/$APPLICATION_NAME.git
#           git clone https://$git_username:$git_token@github.com/$ORGANIZATION_NAME/knot-onboarding-resources.git

#           # Change openapi.yml
#           cp knot-onboarding-resources/products/$APPLICATION_NAME/openapi.yml $APPLICATION_NAME/specification/src/main/resources/openapi.yml

#           # Set credentials
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

#           # Commit and push the changes
#           cd $APPLICATION_NAME
#           git add .
#           git commit -m "Changed openapi.yml"
#           git push
# {{- end }}
