{{- range $user := .Values.users }}
{{- if $user.sealedToken }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ $user.name }}-token
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    token: {{ $user.sealedtoken }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: {{ $user.name }}-token
      namespace: {{ $.Release.Namespace }}
{{- end -}}  
{{- end -}}         
