{{- if not (eq .Values.technology "java-restclient") -}}
{{- if .Values.secret.app -}}
{{- if .Values.secret.app.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-code-secret
  annotations:
    "helm.sh/hook-weight": "-10"
  labels:
    app: {{ .Values.name }}
data:
  name: {{ .Values.secret.app.data.name }}
  type: {{ .Values.secret.app.data.type }}
  tier: {{ .Values.secret.app.data.tier }}
  dbVersion: {{ .Values.secret.app.data.dbVersion }}
  user: {{ .Values.secret.app.data.user }}
  password: {{ .Values.secret.app.data.password }}
# stringData:
#   {{- toYaml .Values.secret.app.data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}