{{- if .Values.serverless }}
{{- if .Values.serverless.createFunctionApp }}
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: "{{ $.Values.name }}-azfunc"
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./azfunc_terraform
  sourceRef:
    kind: GitRepository
    name: terraform-gitops
    namespace: flux-system
  vars:
  - name: project
    value: {{ $.Values.name }}
  - name: environment
    value: dev
  - name: location
    value: "westeurope"
  - name: applicationStack
    value: {{ $.Values.serverless.applicationStack }}
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: azure-service-principal
---
{{- end }}
{{- end }}
